/*
 * This source file was generated by the Gradle 'init' task
 */
package fibonacy;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter a Fibonanci number: ");
        int x = scanner.nextInt();
        scanner.close();
        System.out.println("Calculating");
        int a = 0, b = 1;
        if (x >= 0) {
            System.out.println("f0 = " + a);
        }
        if (x >= 1) {
            System.out.println("f1 = " + b);
        }
        for (int i = 2; i <= x; i++) {
            int c = a + b;
            a = b;
            b = c;
            System.out.println("f" + i + " = " + b);
        }
        System.out.println("Value of Fibonacci is " + b);
    }

}
