/*
 * This source file was generated by the Gradle 'init' task
 */
package salary;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Scanner scanner = new Scanner(System.in);
        System.out.print("Input your salary : ");
        double x = scanner.nextDouble();
        scanner.close();
        if(x <= 15000) {
            x = x * 0.05;
        } else {
            x = 15000 * 0.05;
        }
        System.out.print("Your Welfare is "+ x + " Baht");
    }
}

    }
}
